### ISSUE TITLE
sigkit not compatible with latest stable

### ISSUE THREAD

**Issue by psifertex** [Vector35/sigkit#16]
Not sure what happened (maybe a QT bug with the qt version change?!) but sigkit has lots of exceptions on at least the latest stable: 
```
Opening signature library D:/Program Files/Vector35/BinaryNinja/signatures/linux-x86_64/ubuntu-xenial-amd64-libgcc-5-dev.sig
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 353, in paint
    style.drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 413, in paint
    options.widget.style().drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 353, in paint
    style.drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 413, in paint
    options.widget.style().drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 353, in paint
    style.drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_sigkit\sigexplorer.py", line 413, in paint
    options.widget.style().drawControl(QStyle.CE_ItemViewItem, option, painter, option.widget)
RuntimeError: Internal C++ object (PySide2.QtWidgets.QProxyStyle) already deleted.```

**Comment by stong** [comment]
This bug has been rectified. Get pro gamered on noob
